const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET
  ? process.env.ACCESS_TOKEN_SECRET
  : 'eyJleHBfbGVld2F5IjozMCwiZXhwIjoxNjIyMTk5MDMxLCJuYmZfbGVld2F';
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET
  ? process.env.REFRESH_TOKEN_SECRET
  : '5IjozMCwibmJmIjoxNjIyMTk3MjMxLCJhdXRoX3ZhbGlkYXRlZCI6dHJ1Za';
const ACCESS_TOKEN_EXPIRES = process.env.ACCESS_TOKEN_EXPIRES
  ? process.env.ACCESS_TOKEN_EXPIRES
  : '60s';
const REFRESH_TOKEN_EXPIRES = process.env.REFRESH_TOKEN_EXPIRES
  ? process.env.REFRESH_TOKEN_EXPIRES
  : '1h';

module.exports = {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_EXPIRES,
};
